### ISSUE TITLE
Add source data to repo?

### ISSUE THREAD

**Issue by MathewBiddle** [chiaweh2/CEFI-info-hub-list#1]
Hi @chiaweh2 do you mind adding the source spreadsheet that feeds https://psl.noaa.gov/data/fisheries/ to this repo? Preferably as a csv file.

I'd like to test some new tools and this is a perfect opportunity.

Thanks for putting this together!

**Comment by chiaweh2** [comment]
Hi @MathewBiddle The source file is in Javascript format at the moment maintained by Cathy for creating the demo search tool. But we will definitely discuss if we can have a csv or json format file that is more shareable and distributable. Sorry that I cannot provide the file at the moment.

I am happy to help and thank you for the great idea and useful input!

**Comment by chiaweh2** [comment]
@MathewBiddle The json file is in the data/ directory now!
