### ISSUE TITLE
Inconsistancy between the variable definitions and the values for the resources

### ISSUE THREAD

**Issue by MathewBiddle** [chiaweh2/CEFI-info-hub-list#29]
For the `cvar` definitions, you can see that the keys range from 0-44.
https://github.com/chiaweh2/CEFI-info-hub-list/blob/a1898e0aa2d45437490653d20288d83f5673b256/data/cefi_list.json#L70-L117

However, some of the resources reference a cvar of `45`. 

https://github.com/chiaweh2/CEFI-info-hub-list/blob/a1898e0aa2d45437490653d20288d83f5673b256/data/cefi_list.json#L1792

I think there might be an issue with indexes as the definitions were written (or as they are referenced for each resource). Not sure where things went wrong...

_I think_ `cvar` is the only one with this issue.

**Comment by chiaweh2** [comment]
Thank you for catching this! I will see what happened on the missing indexing and check for other possible missing index.

**Comment by MathewBiddle** [comment]
Also, `cregions` is missing `16`:
https://github.com/chiaweh2/CEFI-info-hub-list/blob/a1898e0aa2d45437490653d20288d83f5673b256/data/cefi_list.json#L197-L198

**Comment by chiaweh2** [comment]
> Also, `cregions` is missing `16`:
> 
> https://github.com/chiaweh2/CEFI-info-hub-list/blob/a1898e0aa2d45437490653d20288d83f5673b256/data/cefi_list.json#L197-L198

This I will need to double check with Cathy about the missing index. Thank you for catching this!
