### ISSUE TITLE
Add gha to validate json

### ISSUE THREAD

**Issue by MathewBiddle** [chiaweh2/CEFI-info-hub-list#8]
We should add something that validates the json every time it is updated. If the json doesn't validate the PR shouldn't get merged.

Could be as simple as 
```
import json
with open('./data/cefi_list.json') as f:
   json.load(f)
```

Although that is failing at the moment with:
```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 52778: character maps to <undefined>
```

**Comment by chiaweh2** [comment]
That is a good idea. I agree.

**Comment by chiaweh2** [comment]
#14
